import * as Joi from 'joi';

export const validationSchema = Joi.object({
  APP_PORT: Joi.number().default(3000),
  JWT_SECRET: Joi.string().required(),
  JWT_EXPIRES_IN: Joi.string().default('15m'),
  JWT_REFRESH_SECRET: Joi.string().required(),
  JWT_REFRESH_EXPIRES_IN: Joi.string().default('7d'),
  POSTGRES_HOST: Joi.string().hostname().default('postgres'),
  POSTGRES_PORT: Joi.number().default(5432),
  POSTGRES_USER: Joi.string().default('postgres'),
  POSTGRES_PASSWORD: Joi.string().default('postgres'),
  POSTGRES_DB: Joi.string().default('financial_app'),
  REDIS_HOST: Joi.string().default('redis'),
  REDIS_PORT: Joi.number().default(6379),
  KAFKA_CLIENT_ID: Joi.string().default('financial-app'),
  KAFKA_BROKERS: Joi.string().default('kafka:9092'),
  KAFKA_ENABLED: Joi.boolean().default(true),
  NOTIFICATIONS_MODE: Joi.string().valid('real', 'stub').default('stub'),
  WEBSOCKET_ENABLED: Joi.boolean().default(true),
  WEBSOCKET_CORS_ORIGIN: Joi.string().default('*'),
  NOTIFICATIONS_KAFKA_CONSUMER_ENABLED: Joi.boolean().default(false),
  NOTIFICATIONS_KAFKA_CONSUMER_GROUP_ID: Joi.string().default('financial-app-notifications'),
  FIREBASE_PROJECT_ID: Joi.string().allow('', null),
  FIREBASE_CLIENT_EMAIL: Joi.string().allow('', null),
  FIREBASE_PRIVATE_KEY: Joi.string().allow('', null),
  FIREBASE_APP_ID: Joi.string().allow('', null),
  SENDGRID_API_KEY: Joi.string().allow('', null),
  SENDGRID_FROM_EMAIL: Joi.string().allow('', null),
  SENDGRID_FROM_NAME: Joi.string().allow('', null),
  WEBHOOK_ENABLED: Joi.boolean().default(false),
  WEBHOOK_URL: Joi.string().allow('', null),
  WEBHOOK_SECRET: Joi.string().allow('', null),
  OAUTH_MODE: Joi.string().valid('stub', 'real').default('stub'),
  OAUTH_PROVIDER: Joi.string().default('keycloak'),
  OAUTH_TOKEN_URL: Joi.string().allow('', null),
  OAUTH_CLIENT_ID: Joi.string().allow('', null),
  OAUTH_CLIENT_SECRET: Joi.string().allow('', null),
  KYC_PROVIDER_MODE: Joi.string().valid('stub', 'real').default('stub'),
  KYC_PROVIDER_NAME: Joi.string().default('stub'),
  KYC_STORAGE_MODE: Joi.string().valid('stub', 'real').default('stub'),
  KYC_STORAGE_PATH: Joi.string().default('storage/kyc'),
  KYC_STORAGE_BASE_URL: Joi.string().default('stub://kyc'),
  INTERBANK_MODE: Joi.string().valid('stub', 'real').default('stub'),
  INTERBANK_PROVIDER: Joi.string().default('stub'),
  INTERBANK_ENDPOINT: Joi.string().allow('', null),
  INTERBANK_API_KEY: Joi.string().allow('', null),
  INTERBANK_RETRY_MAX_ATTEMPTS: Joi.number().default(3),
  INTERBANK_RETRY_BACKOFF_MS: Joi.number().default(250),
  INTERBANK_STUB_FAILURE_RATE: Joi.string().default('0'),
  SCHEDULER_ENABLED: Joi.boolean().default(false),
  SCHEDULER_POLL_INTERVAL_MS: Joi.number().default(30000),
  SCHEDULER_RETRY_BACKOFF_MS: Joi.number().default(60000),
  SCHEDULER_MAX_ATTEMPTS: Joi.number().default(3),
  AUDIT_WORM_MODE: Joi.string().valid('stub', 'off', 'real').default('stub'),
  AUDIT_WORM_PATH: Joi.string().default('storage/audit_worm.log'),
  CARD_VAULT_MODE: Joi.string().valid('stub', 'real').default('stub'),
  CARD_TOKENIZATION_SECRET: Joi.string().default('stub-token'),
  CARD_ENCRYPTION_KEY: Joi.string().allow('', null),
  METRICS_ENABLED: Joi.boolean().default(true),
  TRACING_ENABLED: Joi.boolean().default(true),
  HTTPS_ENABLED: Joi.boolean().default(false),
  HTTPS_KEY_PATH: Joi.string().allow('', null),
  HTTPS_CERT_PATH: Joi.string().allow('', null),
  HTTPS_CA_PATH: Joi.string().allow('', null),
  LEDGER_EVENT_SIGNING_ENABLED: Joi.boolean().default(false),
  LEDGER_EVENT_HMAC_SECRET: Joi.string().allow('', null),
  POSTGRES_REPLICA_ENABLED: Joi.boolean().default(false),
  REDIS_SENTINEL_ENABLED: Joi.boolean().default(false),
  KAFKA_CLUSTER_BROKERS: Joi.string().allow('', null),
});
